[tasks.check-all]
description = "Run all checks"
dependencies = ["check", "clippy", "fmt"]

[tasks.check]
command = "cargo"
args = ["check"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-features", "--all-targets", "--locked"]

[tasks.fmt]
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.fmt-fix]
command = "cargo"
args = ["fmt"]
